//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKC_IS.DataAccess.Model.AutoMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class AP_HISTORIE
    {
        public int ID { get; set; }
        public int TABULKA { get; set; }
        public int ID_RECORD { get; set; }
        public int PORADI { get; set; }
        public int STAV { get; set; }
        public Nullable<System.DateTime> D_OD_DATA { get; set; }
        public int ID_USER { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual SY_TABULKA SY_TABULKA { get; set; }
        public virtual SY_STAV SY_STAV { get; set; }
    }
}
