//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKC_IS.DataAccess.Model.AutoMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class CISELNIK_DEFINICE
    {
        public int ID { get; set; }
        public string DOMENA { get; set; }
        public string NAZEV_CISELNIKU { get; set; }
        public string POPIS { get; set; }
        public string DOMENA_M { get; set; }
        public string MASKA { get; set; }
        public string KOD_VYZNAM { get; set; }
        public string KOD_M_VYZNAM { get; set; }
        public string TXT1 { get; set; }
        public string TXT2 { get; set; }
        public string L0_VYZNAM { get; set; }
        public string L1_VYZNAM { get; set; }
        public string L2_VYZNAM { get; set; }
        public string L3_VYZNAM { get; set; }
        public string L4_VYZNAM { get; set; }
        public string L5_VYZNAM { get; set; }
        public string L6_VYZNAM { get; set; }
        public string L7_VYZNAM { get; set; }
        public string L8_VYZNAM { get; set; }
        public string L9_VYZNAM { get; set; }
    }
}
