//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKC_IS.DataAccess.Model.AutoMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class CISELNIK_DATA
    {
        public int ID { get; set; }
        public string DOMENA { get; set; }
        public string KOD { get; set; }
        public string POPIS { get; set; }
        public Nullable<int> PORADI { get; set; }
        public string KOD_M { get; set; }
        public string TXT1 { get; set; }
        public string TXT2 { get; set; }
        public Nullable<bool> L_0 { get; set; }
        public Nullable<bool> L_1 { get; set; }
        public Nullable<bool> L_2 { get; set; }
        public Nullable<bool> L_3 { get; set; }
        public Nullable<bool> L_4 { get; set; }
        public Nullable<bool> L_5 { get; set; }
        public Nullable<bool> L_6 { get; set; }
        public Nullable<bool> L_7 { get; set; }
        public Nullable<bool> L_8 { get; set; }
        public Nullable<bool> L_9 { get; set; }
    }
}
