//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKC_IS.DataAccess.Model.AutoMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESP_LOG
    {
        public int ID { get; set; }
        public int ID_STROJ { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> ID_op { get; set; }
        public Nullable<int> Hodnota1 { get; set; }
        public Nullable<int> Hodnota2 { get; set; }
        public Nullable<double> Hodnota3 { get; set; }
        public Nullable<double> Hodnota4 { get; set; }
        public Nullable<double> Hodnota5 { get; set; }
    
        public virtual STROJ STROJ { get; set; }
    }
}
