//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKC_IS.DataAccess.Model.AutoMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORMA()
        {
            this.FORMA_OPRAVA = new HashSet<FORMA_OPRAVA>();
            this.MEZNI_VZOREK = new HashSet<MEZNI_VZOREK>();
            this.VZORKOVANI = new HashSet<VZORKOVANI>();
            this.ZAKAZKA = new HashSet<ZAKAZKA>();
        }
    
        public int ID { get; set; }
        public string ZAFO_Forma { get; set; }
        public string ZAVY_Vyrobce { get; set; }
        public string PocetKavit { get; set; }
        public Nullable<double> CyklusCas { get; set; }
        public Nullable<System.DateTime> RokVyroby { get; set; }
        public string Umisteni { get; set; }
        public Nullable<double> Hmotnost { get; set; }
        public Nullable<System.DateTime> DatumZadani { get; set; }
        public int STAV { get; set; }
        public Nullable<int> STAV_NASLEDUJICI { get; set; }
        public int C_USER { get; set; }
        public System.DateTime C_DATE { get; set; }
        public Nullable<int> M_USER { get; set; }
        public Nullable<System.DateTime> M_DATE { get; set; }
        public Nullable<int> PocetVP { get; set; }
    
        public virtual SY_STAV SY_STAV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORMA_OPRAVA> FORMA_OPRAVA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEZNI_VZOREK> MEZNI_VZOREK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VZORKOVANI> VZORKOVANI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZAKAZKA> ZAKAZKA { get; set; }
    }
}
