//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKC_IS.DataAccess.Model.AutoMapping
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConnectionMap_RKC_Database : DbContext
    {
        public ConnectionMap_RKC_Database()
            : base("name=ConnectionMap_RKC_Database")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AP_HISTORIE> AP_HISTORIE { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<CISELNIK_DATA> CISELNIK_DATA { get; set; }
        public virtual DbSet<CISELNIK_DEFINICE> CISELNIK_DEFINICE { get; set; }
        public virtual DbSet<ESP_LOG> ESP_LOG { get; set; }
        public virtual DbSet<FORMA> FORMA { get; set; }
        public virtual DbSet<FORMA_OPRAVA> FORMA_OPRAVA { get; set; }
        public virtual DbSet<GRUPA> GRUPA { get; set; }
        public virtual DbSet<KONSTANTY> KONSTANTY { get; set; }
        public virtual DbSet<MATERIAL> MATERIAL { get; set; }
        public virtual DbSet<MEZNI_VZOREK> MEZNI_VZOREK { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<SESTAVA> SESTAVA { get; set; }
        public virtual DbSet<SESTAVA_DEFINICE> SESTAVA_DEFINICE { get; set; }
        public virtual DbSet<SMENA> SMENA { get; set; }
        public virtual DbSet<STROJ> STROJ { get; set; }
        public virtual DbSet<STROJ_GRUPA> STROJ_GRUPA { get; set; }
        public virtual DbSet<STROJ_PARAMETR> STROJ_PARAMETR { get; set; }
        public virtual DbSet<STROJ_PORUCHA> STROJ_PORUCHA { get; set; }
        public virtual DbSet<STROJ_UDRZBA> STROJ_UDRZBA { get; set; }
        public virtual DbSet<SY_FORMULAR> SY_FORMULAR { get; set; }
        public virtual DbSet<SY_MODUL> SY_MODUL { get; set; }
        public virtual DbSet<SY_MODUL_ROLE> SY_MODUL_ROLE { get; set; }
        public virtual DbSet<SY_POLOZKA> SY_POLOZKA { get; set; }
        public virtual DbSet<SY_POLOZKA_STAV> SY_POLOZKA_STAV { get; set; }
        public virtual DbSet<SY_PRECHOD> SY_PRECHOD { get; set; }
        public virtual DbSet<SY_STAV> SY_STAV { get; set; }
        public virtual DbSet<SY_TABULKA> SY_TABULKA { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<USER_GRUPA> USER_GRUPA { get; set; }
        public virtual DbSet<USER_ROLE> USER_ROLE { get; set; }
        public virtual DbSet<USER_VZORKOVANI> USER_VZORKOVANI { get; set; }
        public virtual DbSet<UserClaim> UserClaim { get; set; }
        public virtual DbSet<UserLogin> UserLogin { get; set; }
        public virtual DbSet<VYROBA_ZAZNAM> VYROBA_ZAZNAM { get; set; }
        public virtual DbSet<VZORKOVANI> VZORKOVANI { get; set; }
        public virtual DbSet<WORKMONITOR> WORKMONITOR { get; set; }
        public virtual DbSet<ZAKAZKA> ZAKAZKA { get; set; }
        public virtual DbSet<ZAKAZKA_SAP> ZAKAZKA_SAP { get; set; }
    }
}
