//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKC_IS.DataAccess.Model.AutoMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATERIAL()
        {
            this.MATERIAL1 = new HashSet<MATERIAL>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_M { get; set; }
        public Nullable<int> ID_ZAKAZKA { get; set; }
        public Nullable<int> ID_VZORKOVANI { get; set; }
        public string ZAMA_Material { get; set; }
        public Nullable<double> MnozstviSpotr { get; set; }
        public Nullable<double> MnozstviPlan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIAL> MATERIAL1 { get; set; }
        public virtual MATERIAL MATERIAL2 { get; set; }
        public virtual VZORKOVANI VZORKOVANI { get; set; }
        public virtual ZAKAZKA ZAKAZKA { get; set; }
    }
}
