//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKC_IS.DataAccess.Model.AutoMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class SY_FORMULAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SY_FORMULAR()
        {
            this.SY_POLOZKA = new HashSet<SY_POLOZKA>();
        }
    
        public int ID { get; set; }
        public int ID_MODUL { get; set; }
        public string NAZEV { get; set; }
        public string TABULKA { get; set; }
    
        public virtual SY_MODUL SY_MODUL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SY_POLOZKA> SY_POLOZKA { get; set; }
    }
}
