//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKC_IS.DataAccess.Model.AutoMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class SY_MODUL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SY_MODUL()
        {
            this.SY_FORMULAR = new HashSet<SY_FORMULAR>();
            this.SY_MODUL_ROLE = new HashSet<SY_MODUL_ROLE>();
        }
    
        public int ID { get; set; }
        public string TABULKA { get; set; }
        public int STAV { get; set; }
        public string NAZEV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SY_FORMULAR> SY_FORMULAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SY_MODUL_ROLE> SY_MODUL_ROLE { get; set; }
    }
}
