//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKC_IS.DataAccess.Model.AutoMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class SY_MODUL_ROLE
    {
        public int ID { get; set; }
        public Nullable<int> ID_MODUL { get; set; }
        public Nullable<int> ID_ROLE { get; set; }
    
        public virtual ROLE ROLE { get; set; }
        public virtual SY_MODUL SY_MODUL { get; set; }
    }
}
