//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKC_IS.DataAccess.Model.AutoMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class SY_POLOZKA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SY_POLOZKA()
        {
            this.SY_POLOZKA_STAV = new HashSet<SY_POLOZKA_STAV>();
        }
    
        public int ID { get; set; }
        public int ID_FORM { get; set; }
        public string POLOZKA { get; set; }
        public int PORADI { get; set; }
        public string TYP { get; set; }
    
        public virtual SY_FORMULAR SY_FORMULAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SY_POLOZKA_STAV> SY_POLOZKA_STAV { get; set; }
    }
}
