//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKC_IS.DataAccess.Model.AutoMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class SY_PRECHOD
    {
        public int ID { get; set; }
        public string TABULKA { get; set; }
        public int ZE_STAVU { get; set; }
        public int DO_STAVU { get; set; }
        public string POPIS { get; set; }
        public bool L_PLATI { get; set; }
    }
}
