//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKC_IS.DataAccess.Model.AutoMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class SY_POLOZKA_STAV
    {
        public int ID { get; set; }
        public int ID_POLOZKA { get; set; }
        public int STAV { get; set; }
        public Nullable<int> ID_ROLE_VIEW { get; set; }
        public Nullable<int> ID_ROLE_EDIT { get; set; }
    
        public virtual ROLE ROLE { get; set; }
        public virtual ROLE ROLE1 { get; set; }
        public virtual SY_POLOZKA SY_POLOZKA { get; set; }
        public virtual SY_STAV SY_STAV { get; set; }
    }
}
