//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKC_IS.DataAccess.Model.AutoMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class SY_STAV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SY_STAV()
        {
            this.AP_HISTORIE = new HashSet<AP_HISTORIE>();
            this.FORMA = new HashSet<FORMA>();
            this.FORMA_OPRAVA = new HashSet<FORMA_OPRAVA>();
            this.GRUPA = new HashSet<GRUPA>();
            this.MEZNI_VZOREK = new HashSet<MEZNI_VZOREK>();
            this.ROLE = new HashSet<ROLE>();
            this.SESTAVA_DEFINICE = new HashSet<SESTAVA_DEFINICE>();
            this.STROJ = new HashSet<STROJ>();
            this.STROJ_PORUCHA = new HashSet<STROJ_PORUCHA>();
            this.STROJ_UDRZBA = new HashSet<STROJ_UDRZBA>();
            this.SY_POLOZKA_STAV = new HashSet<SY_POLOZKA_STAV>();
            this.USER = new HashSet<USER>();
            this.VYROBA_ZAZNAM = new HashSet<VYROBA_ZAZNAM>();
            this.VZORKOVANI = new HashSet<VZORKOVANI>();
            this.ZAKAZKA = new HashSet<ZAKAZKA>();
        }
    
        public int ID { get; set; }
        public string TABULKA { get; set; }
        public int STAV { get; set; }
        public string POPIS { get; set; }
        public bool L_PLATI { get; set; }
        public string BARVA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AP_HISTORIE> AP_HISTORIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORMA> FORMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORMA_OPRAVA> FORMA_OPRAVA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRUPA> GRUPA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEZNI_VZOREK> MEZNI_VZOREK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROLE> ROLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SESTAVA_DEFINICE> SESTAVA_DEFINICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STROJ> STROJ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STROJ_PORUCHA> STROJ_PORUCHA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STROJ_UDRZBA> STROJ_UDRZBA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SY_POLOZKA_STAV> SY_POLOZKA_STAV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VYROBA_ZAZNAM> VYROBA_ZAZNAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VZORKOVANI> VZORKOVANI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZAKAZKA> ZAKAZKA { get; set; }
    }
}
