//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKC_IS.DataAccess.Model.AutoMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_VZORKOVANI
    {
        public int ID { get; set; }
        public int ID_USER { get; set; }
        public int ID_VZORKOVANI { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual VZORKOVANI VZORKOVANI { get; set; }
    }
}
