//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKC_IS.DataAccess.Model.AutoMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.AP_HISTORIE = new HashSet<AP_HISTORIE>();
            this.FORMA_OPRAVA = new HashSet<FORMA_OPRAVA>();
            this.MEZNI_VZOREK = new HashSet<MEZNI_VZOREK>();
            this.STROJ_PORUCHA = new HashSet<STROJ_PORUCHA>();
            this.STROJ_UDRZBA = new HashSet<STROJ_UDRZBA>();
            this.USER_GRUPA = new HashSet<USER_GRUPA>();
            this.USER_ROLE = new HashSet<USER_ROLE>();
            this.USER_VZORKOVANI = new HashSet<USER_VZORKOVANI>();
            this.VYROBA_ZAZNAM = new HashSet<VYROBA_ZAZNAM>();
            this.UserClaim = new HashSet<UserClaim>();
            this.UserLogin = new HashSet<UserLogin>();
        }
    
        public int ID { get; set; }
        public string ZAOR_organizace { get; set; }
        public string Jmeno { get; set; }
        public string Prijmeni { get; set; }
        public Nullable<int> OsobniCislo { get; set; }
        public string PhoneNumber { get; set; }
        public string Obec { get; set; }
        public string Ulice { get; set; }
        public string CisloDomu { get; set; }
        public Nullable<int> PSC { get; set; }
        public Nullable<System.DateTime> DatumNastup { get; set; }
        public string PlatovaTrida { get; set; }
        public string Smena { get; set; }
        public Nullable<System.DateTime> CasPrihlaseni { get; set; }
        public int C_USER { get; set; }
        public Nullable<int> M_USER { get; set; }
        public System.DateTime C_DATE { get; set; }
        public Nullable<System.DateTime> M_DATE { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string Email { get; set; }
        public int STAV { get; set; }
        public Nullable<int> STAV_NASLEDUJICI { get; set; }
        public Nullable<bool> EmailConfirmed { get; set; }
        public string SecurityStamp { get; set; }
        public Nullable<bool> PhoneNumberConfirmed { get; set; }
        public Nullable<bool> TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public Nullable<bool> LockoutEnabled { get; set; }
        public Nullable<int> AccessFailedCount { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
        public string ActivationToken { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AP_HISTORIE> AP_HISTORIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORMA_OPRAVA> FORMA_OPRAVA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEZNI_VZOREK> MEZNI_VZOREK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STROJ_PORUCHA> STROJ_PORUCHA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STROJ_UDRZBA> STROJ_UDRZBA { get; set; }
        public virtual SY_STAV SY_STAV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_GRUPA> USER_GRUPA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_ROLE> USER_ROLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_VZORKOVANI> USER_VZORKOVANI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VYROBA_ZAZNAM> VYROBA_ZAZNAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserClaim> UserClaim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLogin> UserLogin { get; set; }
    }
}
