//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKC_IS.DataAccess.Model.AutoMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class VYROBA_ZAZNAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VYROBA_ZAZNAM()
        {
            this.VYROBA_ZAZNAM1 = new HashSet<VYROBA_ZAZNAM>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_M { get; set; }
        public Nullable<int> ID_ZAKAZKA { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public Nullable<double> CasPrace { get; set; }
        public Nullable<int> OK { get; set; }
        public Nullable<int> NOK { get; set; }
        public string Poznamka { get; set; }
        public Nullable<System.DateTime> TimeStart { get; set; }
        public Nullable<System.DateTime> TimeEnd { get; set; }
        public int C_USER { get; set; }
        public System.DateTime C_DATE { get; set; }
        public Nullable<int> M_USER { get; set; }
        public Nullable<System.DateTime> M_DATE { get; set; }
        public int STAV { get; set; }
        public Nullable<int> STAV_NASLEDUJICI { get; set; }
        public Nullable<bool> IsSelected { get; set; }
    
        public virtual SY_STAV SY_STAV { get; set; }
        public virtual USER USER { get; set; }
        public virtual ZAKAZKA ZAKAZKA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VYROBA_ZAZNAM> VYROBA_ZAZNAM1 { get; set; }
        public virtual VYROBA_ZAZNAM VYROBA_ZAZNAM2 { get; set; }
    }
}
