//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKC_IS.DataAccess.Model.AutoMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKMONITOR
    {
        public int ID { get; set; }
        public Nullable<int> ID_STROJ { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> Type1 { get; set; }
        public string Type2 { get; set; }
        public string NazevStroje { get; set; }
        public string Input { get; set; }
        public string Value { get; set; }
        public string Xmlmix { get; set; }
    
        public virtual STROJ STROJ { get; set; }
    }
}
