//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKC_IS.DataAccess.Model.AutoMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAKAZKA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZAKAZKA()
        {
            this.MATERIAL = new HashSet<MATERIAL>();
            this.VYROBA_ZAZNAM = new HashSet<VYROBA_ZAZNAM>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_STROJ { get; set; }
        public Nullable<int> ID_FORMA { get; set; }
        public int CisloZakazka { get; set; }
        public string Oznaceni { get; set; }
        public string NazevProces { get; set; }
        public Nullable<int> PlanovaneMnozstviNa { get; set; }
        public Nullable<int> VyrobenoZahlaseno { get; set; }
        public Nullable<int> ZbyvajiciMnozstvi { get; set; }
        public string Hodnota { get; set; }
        public string KonecnyT { get; set; }
        public Nullable<System.DateTime> DatumNasazeni { get; set; }
        public string Pos { get; set; }
        public Nullable<double> Nasobnost { get; set; }
        public Nullable<double> CyklusCas { get; set; }
        public Nullable<double> DobaPriprava { get; set; }
        public Nullable<double> DobaVyroba { get; set; }
        public Nullable<double> DobaPripravaVyroba { get; set; }
        public Nullable<int> Priorita { get; set; }
        public string PoznamkaNaVP { get; set; }
        public Nullable<double> DelkaVymeny { get; set; }
        public Nullable<double> CyklusCasReal { get; set; }
        public Nullable<System.DateTime> DatumUkonceni { get; set; }
        public Nullable<int> ZahlaseneMnozstvi { get; set; }
        public Nullable<int> ZaskladneneMnozstvi { get; set; }
        public int C_USER { get; set; }
        public System.DateTime C_DATE { get; set; }
        public Nullable<int> M_USER { get; set; }
        public Nullable<System.DateTime> M_DATE { get; set; }
        public int STAV { get; set; }
        public Nullable<int> STAV_NASLEDUJICI { get; set; }
        public Nullable<int> PocetlLidiNaVP { get; set; }
    
        public virtual FORMA FORMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIAL> MATERIAL { get; set; }
        public virtual STROJ STROJ { get; set; }
        public virtual SY_STAV SY_STAV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VYROBA_ZAZNAM> VYROBA_ZAZNAM { get; set; }
    }
}
