//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKC_IS.DataAccess.Model.AutoMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAKAZKA_SAP
    {
        public int ID { get; set; }
        public string CisloZakazka { get; set; }
        public string CisloMaterial { get; set; }
        public string Oznaceni { get; set; }
        public string PlanMnozstviNa { get; set; }
        public string VyrobenoZahlasenoMnoz { get; set; }
        public string ZbyvajiciMnozstvi { get; set; }
        public string Hodnota { get; set; }
        public string KonecnyT { get; set; }
        public string VyrobniStre { get; set; }
        public string Pos { get; set; }
        public string NazevProces { get; set; }
        public string Nasobnost { get; set; }
        public string CyklusCas { get; set; }
        public string DobaPriprava { get; set; }
        public string DobaVyroba { get; set; }
        public string DobaPripravaVyroba { get; set; }
        public string Forma { get; set; }
        public string GranulatCislo { get; set; }
        public string GranulatMnozstvi { get; set; }
        public string MBCislo { get; set; }
        public string MBMnozstvi { get; set; }
        public string PlanovanyStroj { get; set; }
        public string FolieCislo { get; set; }
        public string FolieMnozstvi { get; set; }
        public string Priorita { get; set; }
        public string PoznamkaNaVP { get; set; }
    }
}
