// <auto-generated />
namespace RKC_IS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migraceMyUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migraceMyUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202004060159157_migraceMyUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
